export enum ProcessCrawlToken {
    CRAWL_NEW_CONF_JOB_NAME = 'CRAWL_NEW_CONF_JOB_NAME',
    CRAWL_CONF_QUEUE_NAME = 'CRAWL_CONF_QUEUE',
    CRAWL_CONF_QUEUE_PREFIX = 'CRAWL_CONF',
    CRAWL_UPDATE_CONF_JOB_NAME = 'CRAWL_UPDATE_CONF_JOB_NAME',
}

